name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/go-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/go-app:latest

  deploy:
    name: Update Helm Values
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Helm values
        run: |
          cd helm
          cd my-go-app-chart
          yq eval '.image.repository = "${{ secrets.DOCKERHUB_USERNAME }}/my-go-app"' -i values.yaml
          yq eval '.image.tag = "${{ github.sha }}"' -i values.yaml

      - name: Commit and push updated values
        run: |
          git config --global user.name 'IfeOlaitan'
          git config --global user.email 'ifeoluwa1201@gmail.com'
          git add helm/my-go-app-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push